language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
before_deploy:
  - npm install -g netlify-cli
before_script:
  - npm install -g gridsome-cli
  - npm install
script:
  - gridsome build
deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist --prod
  on:
    branch: master